apiVersion: v1
kind: Secret
metadata:
  name: openobserve
  namespace: observability

type: Opaque
# Dummy values only; replace before deployment.
data:
  username: ZHVtbXktdXNlcg==
  password: ZHVtbXktcGFzc3dvcmQ=
